name: imager
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - python=3.8
  - pillow
  - pip
  - jupyter
  - nb_conda
  - opencv
  - pip:
      - harvesters
      - git+https://github.com/elerac/polanalyser


